apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignition
  template:
    metadata:
      labels:
        app: ignition
    spec:
      containers:
      - name: ignition-test
        image: inductiveautomation/ignition:8.1.30
        args:
          - "-n"
          - "docker-test"
          - "-a"
          - "localhost"
          - "-h"
          - "9088"
          - "-s"
          - "9043"
        ports:
        - containerPort: 9088
        livenessProbe:
          httpGet:
            path: /probe
            port: 9088
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
