apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
spec:
  type: NodePort
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 30091
    protocol: TCP
  selector:
    app: node-exporter
