apiVersion: v1
kind: Service
metadata:
  name: openldap-nodeport-service
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30389
