apiVersion: v1
kind: Service
metadata:
  name: ignition-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
spec:
  type: NodePort
  selector:
    app: ignition
  ports:
  - name: web-interface
    protocol: TCP
    port: 8088
    targetPort: 8088
    nodePort: 30088
  - name: opcua
    protocol: TCP
    port: 62541
    targetPort: 62541
    nodePort: 32541
