apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 42nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gogs.default.svc.cluster.local:3000/test/42snippets_inception.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}